export enum locationType {
    river,
    riverMouth,
    riverCliff,
    pond,
    sea,
    pier,
    seaRain,
    flying,
    flyingHybridFlowers,
    flyingPurple,
    flyingLight,
    trees,
    ground,
    flowers,
    whiteFlowers,
    shakeTrees,
    underground,
    pondsSurface,
    pondsRiversSurface,
    treeStumps,
    coconutTrees,
    pushingSnowballs,
    leafDisguise,
    rottenFood,
    shellDisguise,
    onTrash,
    rocksBeach,
    onVillagers,
    rocksShrubsRaining,
    hitRocks,
    underwater,
}

export const locationValues = [
    'River',
    'River Mouth',
    'River (Clifftop)',
    'Pond',
    'Sea',
    'Sea (off pier)',
    'Sea (must be raining)',
    'Flying around everywhere',
    'Flying by hybrid flowers',
    'Flying near purple flowers',
    'Flying (near light)',
    'Resting on trees',
    'On the ground',
    'On flowers',
    'On white flowers',
    'Falls when you shake trees',
    'Underground. Follow your ears to the chirping sound, and dig!',
    'On the surface of ponds',
    'On the surface of ponds and rivers',
    'On tree stumps',
    'On coconut trees',
    'On the ground, pushing snowballs',
    'Near trees, disguised as an item leaf',
    'On rotten food. Drop a turnip on the ground outside, and wait until the following Monday...',
    'On the beach disguised as a white shell',
    'Flying around tyres, boots or cans left on the ground',
    'Found in clusters, on flat rocks on the beach',
    'Found on villagers. If you see a villager with black dots jumping off them, and they complain about feeling itchy, get your net ready...',
    "Found on rocks and shrubs (when it's raining)",
    'Hit a rock with your shovel, and one may pop out',
    "Underwater (dive when you see bubbles)",

];
